# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_cour.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(657, 559)
        self.line_num_cour = QtWidgets.QLineEdit(Dialog)
        self.line_num_cour.setGeometry(QtCore.QRect(20, 60, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.line_num_cour.setFont(font)
        self.line_num_cour.setObjectName("line_num_cour")
        self.MS_e_num_v = QtWidgets.QLabel(Dialog)
        self.MS_e_num_v.setEnabled(True)
        self.MS_e_num_v.setGeometry(QtCore.QRect(20, 120, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MS_e_num_v.setFont(font)
        self.MS_e_num_v.setObjectName("MS_e_num_v")
        self.label_num_e_cour = QtWidgets.QLabel(Dialog)
        self.label_num_e_cour.setGeometry(QtCore.QRect(20, 20, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_num_e_cour.setFont(font)
        self.label_num_e_cour.setObjectName("label_num_e_cour")
        self.MS_e_num_inex = QtWidgets.QLabel(Dialog)
        self.MS_e_num_inex.setEnabled(True)
        self.MS_e_num_inex.setGeometry(QtCore.QRect(20, 150, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.MS_e_num_inex.setFont(font)
        self.MS_e_num_inex.setObjectName("MS_e_num_inex")
        self.BT_confirmer_cour = QtWidgets.QPushButton(Dialog)
        self.BT_confirmer_cour.setGeometry(QtCore.QRect(450, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BT_confirmer_cour.setFont(font)
        self.BT_confirmer_cour.setObjectName("BT_confirmer_cour")
        self.BT_quitter_cour = QtWidgets.QPushButton(Dialog)
        self.BT_quitter_cour.setGeometry(QtCore.QRect(450, 170, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BT_quitter_cour.setFont(font)
        self.BT_quitter_cour.setObjectName("BT_quitter_cour")
        self.CB_cour = QtWidgets.QComboBox(Dialog)
        self.CB_cour.setGeometry(QtCore.QRect(20, 200, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CB_cour.setFont(font)
        self.CB_cour.setObjectName("CB_cour")
        self.list_view_cour = QtWidgets.QListView(Dialog)
        self.list_view_cour.setGeometry(QtCore.QRect(20, 260, 631, 281))
        self.list_view_cour.setObjectName("list_view_cour")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.MS_e_num_v.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Le numero d\'etudiant doit etre numerique et entier</span></p></body></html>"))
        self.label_num_e_cour.setText(_translate("Dialog", "Numero de l\'etudiant"))
        self.MS_e_num_inex.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Ct etudiant est inexistant</span></p></body></html>"))
        self.BT_confirmer_cour.setText(_translate("Dialog", "confirmer"))
        self.BT_quitter_cour.setText(_translate("Dialog", "quitter"))
